const C=window.SCC_CONFIG;
let authToken=sessionStorage.getItem('scc_auth')||'';
let profile=null,quizzes=[],editQuiz=null,activeSession=null,teacherPoll=null,latestResults=[];
let studentState={pin:'',participantId:'',session:null,selected:[],lastQuestionIndex:-1},studentPoll=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(m){const t=$('#toast');t.textContent=m;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2800)}
function showView(v){['home','teacher','student'].forEach(x=>$(`#${x}View`).classList.toggle('hidden',x!==v));if(v==='student')prefillPin();if(v==='teacher')restoreLogin()}
window.showView=showView;
$('#homeBtn').onclick=()=>showView('home');$('#teacherBtn').onclick=()=>showView('teacher');$('#studentBtn').onclick=()=>showView('student');
function prefillPin(){const p=new URLSearchParams(location.search).get('pin');if(p)$('#joinPin').value=p}
async function api(action,payload={}){if(!C.GAS_URL||C.GAS_URL.includes('PASTE_'))throw new Error('尚未設定 GAS_URL');const res=await fetch(C.GAS_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload,authToken})});const data=await res.json();if(!data.ok)throw new Error(data.error||'操作失敗');return data.data}
async function restoreLogin(){if(!C.GAS_URL||C.GAS_URL.includes('PASTE_')){$('#loginConfigHint').classList.remove('hidden');return}const saved=localStorage.getItem('scc_account');if(saved){$('#loginAccount').value=saved;$('#rememberAccount').checked=true}if(!authToken)return;try{profile=await api('me');enterTeacher()}catch(e){sessionStorage.removeItem('scc_auth');authToken=''}}
$('#loginBtn').onclick=async()=>{try{const account=$('#loginAccount').value.trim(),password=$('#loginPassword').value;if(!account||!password)throw new Error('請輸入帳號與密碼');const d=await api('login',{account,password});authToken=d.token;profile=d.user;sessionStorage.setItem('scc_auth',authToken);if($('#rememberAccount').checked)localStorage.setItem('scc_account',account);else localStorage.removeItem('scc_account');$('#loginPassword').value='';enterTeacher()}catch(e){toast(e.message)}};
function enterTeacher(){$('#teacherLogin').classList.add('hidden');$('#teacherShell').classList.remove('hidden');$('#teacherName').textContent=profile.name||profile.account;$('#teacherRole').textContent=profile.role==='admin'?'管理者':'教師';$('#adminTabBtn').classList.toggle('hidden',profile.role!=='admin');showQuizArea();loadQuizzes()}
$('#logoutBtn').onclick=async()=>{try{if(authToken)await api('logout')}catch(e){}clearInterval(teacherPoll);activeSession=null;latestResults=[];$('#sessionControl').classList.add('hidden');$('#noSession').classList.remove('hidden');$('#resultsCard').classList.add('hidden');authToken='';profile=null;sessionStorage.removeItem('scc_auth');$('#teacherShell').classList.add('hidden');$('#teacherLogin').classList.remove('hidden');toast('已登出')};
function showQuizArea(){$('#quizArea').classList.remove('hidden');$('#adminArea').classList.add('hidden');$('#quizEditor').classList.add('hidden');$('#resultsCard').classList.add('hidden')}
$('#quizTabBtn').onclick=showQuizArea;
$('#adminTabBtn').onclick=()=>{$('#quizArea').classList.add('hidden');$('#quizEditor').classList.add('hidden');$('#resultsCard').classList.add('hidden');$('#adminArea').classList.remove('hidden');loadTeachers()};

async function loadQuizzes(){try{quizzes=await api('listQuizzes');renderQuizList()}catch(e){toast(e.message)}}
function renderQuizList(){const box=$('#quizList');if(!quizzes.length){box.innerHTML='<div class="notice">目前還沒有題庫，請按「新增題庫」。</div>';return}box.innerHTML=quizzes.map(q=>`<div class="item"><div><b>${esc(q.title)}</b><div class="meta">${q.questionCount} 題｜${q.mode==='diagnostic'?'診斷模式':'競賽模式'}</div></div><div class="actions"><button class="btn ghost" onclick="openQuiz('${q.id}')">編輯</button><button class="btn primary" onclick="startQuiz('${q.id}')">開始</button></div></div>`).join('')}
$('#newQuizBtn').onclick=()=>{editQuiz={id:'',title:'未命名題庫',mode:'competition',questions:[blankQuestion()]};openEditor()};
function blankQuestion(){return {id:(crypto.randomUUID?.()||String(Date.now()+Math.random())),type:'single',text:'',options:['','','',''],correct:[0],points:1000,timeLimit:30}}
async function openQuiz(id){try{editQuiz=await api('getQuiz',{id});openEditor()}catch(e){toast(e.message)}}window.openQuiz=openQuiz;
function openEditor(){$('#quizEditor').classList.remove('hidden');$('#quizTitle').value=editQuiz.title;$('#quizMode').value=editQuiz.mode;renderQuestionEditors();$('#quizEditor').scrollIntoView({behavior:'smooth'})}
$('#closeEditorBtn').onclick=()=>$('#quizEditor').classList.add('hidden');
$('#addQuestionBtn').onclick=()=>{syncEditor();editQuiz.questions.push(blankQuestion());renderQuestionEditors()};
function renderQuestionEditors(){const b=$('#questionEditors');b.innerHTML=editQuiz.questions.map((q,i)=>`<div class="question-editor" data-i="${i}"><div class="section-title"><h3>第 ${i+1} 題</h3><button class="btn danger" onclick="removeQuestion(${i})">刪除</button></div><div class="grid three"><div class="field"><label>題型</label><select class="q-type"><option value="single" ${q.type==='single'?'selected':''}>單選</option><option value="multiple" ${q.type==='multiple'?'selected':''}>多選</option><option value="truefalse" ${q.type==='truefalse'?'selected':''}>是非</option></select></div><div class="field"><label>分數</label><input class="q-points" type="number" min="0" value="${q.points ?? 1000}"></div><div class="field"><label>時間（秒）</label><input class="q-time" type="number" min="5" value="${q.timeLimit||30}"></div></div><div class="field"><label>題目</label><textarea class="q-text">${esc(q.text)}</textarea></div><div class="options">${(q.type==='truefalse'?['○ 正確','✕ 錯誤']:q.options).map((o,j)=>`<div class="option-row"><input class="q-correct" type="${q.type==='multiple'?'checkbox':'radio'}" name="correct-${i}" value="${j}" ${q.correct.includes(j)?'checked':''}><input class="q-option" type="text" value="${esc(o)}" ${q.type==='truefalse'?'readonly':''}></div>`).join('')}</div></div>`).join('');$$('.q-type').forEach(el=>el.onchange=()=>{syncEditor();const idx=+el.closest('.question-editor').dataset.i,q=editQuiz.questions[idx];if(q.type==='truefalse'){q.options=['○ 正確','✕ 錯誤'];q.correct=[0]}else if(q.options.length<4){q.options=['','','',''];q.correct=[0]}renderQuestionEditors()})}
function syncEditor(){editQuiz.title=$('#quizTitle').value.trim();editQuiz.mode=$('#quizMode').value;$$('.question-editor').forEach(node=>{const i=+node.dataset.i,q=editQuiz.questions[i];q.type=node.querySelector('.q-type').value;q.text=node.querySelector('.q-text').value.trim();q.points=+node.querySelector('.q-points').value||0;q.timeLimit=+node.querySelector('.q-time').value||30;q.options=[...node.querySelectorAll('.q-option')].map(x=>x.value.trim());q.correct=[...node.querySelectorAll('.q-correct:checked')].map(x=>+x.value)})}
function removeQuestion(i){syncEditor();if(editQuiz.questions.length===1)return toast('至少保留一題');editQuiz.questions.splice(i,1);renderQuestionEditors()}window.removeQuestion=removeQuestion;
$('#saveQuizBtn').onclick=async()=>{try{syncEditor();if(!editQuiz.title)throw new Error('請輸入題庫名稱');if(editQuiz.questions.some(q=>!q.text||q.correct.length===0))throw new Error('請完成題目與正確答案');editQuiz=await api('saveQuiz',{quiz:editQuiz});toast('題庫已儲存');await loadQuizzes()}catch(e){toast(e.message)}};
async function startQuiz(id){try{activeSession=await api('startSession',{quizId:id,baseUrl:location.origin+location.pathname});renderSession();clearInterval(teacherPoll);teacherPoll=setInterval(refreshTeacherSession,2000)}catch(e){toast(e.message)}}window.startQuiz=startQuiz;
function renderSession(){if(!activeSession)return;$('#resultsCard').classList.add('hidden');latestResults=[];$('#noSession').classList.add('hidden');$('#sessionControl').classList.remove('hidden');$('#teacherPin').textContent=activeSession.pin;$('#teacherQr').innerHTML='';if(typeof QRCode==='function')new QRCode($('#teacherQr'),{text:activeSession.joinUrl,width:180,height:180});else $('#teacherQr').textContent='QR Code 載入失敗，請使用 PIN 或下方連結加入。';$('#joinUrlText').textContent=activeSession.joinUrl;updateTeacherUI(activeSession)}
async function refreshTeacherSession(){if(!activeSession)return;try{activeSession=await api('getTeacherSession',{pin:activeSession.pin});updateTeacherUI(activeSession)}catch(e){console.warn(e)}}
function updateTeacherUI(s){$('#nextQuestionBtn').disabled=s.status==='finished';$('#endSessionBtn').disabled=s.status==='finished';$('#joinedCount').textContent=s.joinedCount;$('#answeredCount').textContent=s.answeredCount;$('#qNo').textContent=s.questionIndex<0?0:Math.min(s.questionIndex+1,s.totalQuestions);$('#qTotal').textContent=s.totalQuestions;$('#teacherProgress').style.width=(s.totalQuestions&&s.questionIndex>=0?((s.questionIndex+1)/s.totalQuestions*100):0)+'%';$('#teacherQuestion').textContent=s.currentQuestion?.text||'等待開始';const stats=s.optionStats||[],max=Math.max(1,...stats.map(x=>x.count));$('#answerStats').innerHTML=stats.map((x,i)=>`<div class="bar-row"><b>選項 ${i+1}</b><div class="bar"><i style="width:${x.count/max*100}%"></i></div><span>${x.count}</span></div>`).join('');if(s.status==='finished'){clearInterval(teacherPoll);showResults(s)}}
$('#refreshSessionBtn').onclick=refreshTeacherSession;
$('#nextQuestionBtn').onclick=async()=>{try{activeSession=await api('nextQuestion',{pin:activeSession.pin});updateTeacherUI(activeSession)}catch(e){toast(e.message)}};
$('#endSessionBtn').onclick=async()=>{try{activeSession=await api('endSession',{pin:activeSession.pin});updateTeacherUI(activeSession)}catch(e){toast(e.message)}};
function showResults(s){$('#resultsCard').classList.remove('hidden');latestResults=s.results||[];$('#resultsTable').innerHTML=`<table><thead><tr><th>排名</th><th>班級</th><th>座號</th><th>姓名</th><th>分數</th><th>答對</th></tr></thead><tbody>${latestResults.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.className)}</td><td>${esc(r.seatNo)}</td><td>${esc(r.name)}</td><td>${r.score}</td><td>${r.correctCount}/${r.totalQuestions}</td></tr>`).join('')}</tbody></table>`}
$('#exportCsvBtn').onclick=()=>{if(!latestResults.length)return;const rows=[['排名','班級','座號','姓名','分數','答對題數','總題數'],...latestResults.map((r,i)=>[i+1,r.className,r.seatNo,r.name,r.score,r.correctCount,r.totalQuestions])];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`SingChiaClass_${activeSession?.pin||'results'}.csv`;a.click()};

async function loadTeachers(){if(profile?.role!=='admin')return;try{const list=await api('listTeachers');renderTeachers(list)}catch(e){toast(e.message)}}
function renderTeachers(list){$('#teacherTable').innerHTML=`<table><thead><tr><th>帳號</th><th>姓名</th><th>角色</th><th>狀態</th><th>最後登入</th><th>操作</th></tr></thead><tbody>${list.map(x=>`<tr><td>${esc(x.account)}</td><td>${esc(x.name)}</td><td>${x.role==='admin'?'管理者':'教師'}</td><td>${x.enabled?'啟用':'停用'}</td><td>${esc(x.lastLogin||'')}</td><td><button class="btn ghost" onclick="resetPassword('${esc(x.account)}')">重設密碼</button> <button class="btn ${x.enabled?'danger':'primary'}" onclick="toggleTeacher('${esc(x.account)}',${!x.enabled})">${x.enabled?'停用':'啟用'}</button></td></tr>`).join('')}</tbody></table>`}
async function resetPassword(account){const p=prompt(`請輸入 ${account} 的新密碼（至少 6 碼）`);if(!p)return;try{await api('resetTeacherPassword',{account,password:p});toast('密碼已更新');loadTeachers()}catch(e){toast(e.message)}}window.resetPassword=resetPassword;
async function toggleTeacher(account,enabled){try{await api('setTeacherEnabled',{account,enabled});toast('狀態已更新');loadTeachers()}catch(e){toast(e.message)}}window.toggleTeacher=toggleTeacher;
$('#refreshTeachersBtn').onclick=loadTeachers;
$('#teacherCsvFile').onchange=async e=>{const f=e.target.files[0];if(f)$('#teacherCsvText').value=await f.text()};
$('#importTeachersBtn').onclick=async()=>{try{const csv=$('#teacherCsvText').value.trim();if(!csv)throw new Error('請選擇 CSV 或貼上 CSV 內容');const d=await api('importTeachers',{csv});$('#importSummary').classList.remove('hidden');$('#importSummary').textContent=`完成：新增 ${d.created} 筆、更新 ${d.updated} 筆、略過 ${d.skipped} 筆。`;loadTeachers()}catch(e){toast(e.message)}};
$('#addTeacherBtn').onclick=async()=>{try{const teacher={account:$('#newAccount').value.trim(),name:$('#newName').value.trim(),password:$('#newPassword').value,role:$('#newRole').value,enabled:$('#newEnabled').value==='true'};await api('upsertTeacher',{teacher});toast('帳號已儲存');$('#newPassword').value='';loadTeachers()}catch(e){toast(e.message)}};

$('#joinBtn').onclick=async()=>{try{const pin=$('#joinPin').value.trim(),className=$('#studentClass').value.trim(),seatNo=$('#studentNo').value.trim(),name=$('#studentName').value.trim();if(!/^\d{6}$/.test(pin)||!className||!seatNo||!name)throw new Error('請完整填寫 PIN、班級、座號與姓名');const d=await api('joinSession',{pin,className,seatNo,name});studentState={pin,participantId:d.participantId,session:d,selected:[],lastQuestionIndex:-1};localStorage.setItem('scc_student',JSON.stringify({pin,participantId:d.participantId}));$('#joinCard').classList.add('hidden');$('#studentPin').textContent=pin;$('#waitingCard').classList.remove('hidden');renderStudentState(d);clearInterval(studentPoll);studentPoll=setInterval(refreshStudent,1500)}catch(e){toast(e.message)}};
async function refreshStudent(){try{const d=await api('getStudentSession',{pin:studentState.pin,participantId:studentState.participantId});studentState.session=d;renderStudentState(d)}catch(e){console.warn(e)}}
function renderStudentState(s){if(s.status==='finished'){clearInterval(studentPoll);$('#waitingCard').classList.add('hidden');$('#playCard').classList.add('hidden');$('#finishCard').classList.remove('hidden');$('#finalScore').textContent=(s.me?.score||0)+' 分';$('#studentRank').textContent=`排名：${s.me?.rank||'—'}`;return}if(s.questionIndex<0||!s.currentQuestion){$('#waitingCard').classList.remove('hidden');$('#playCard').classList.add('hidden');$('#waitingText').textContent='已成功加入，等待老師開始第一題。';return}if(studentState.lastQuestionIndex!==s.questionIndex){studentState.lastQuestionIndex=s.questionIndex;studentState.selected=[];$('#answerFeedback').classList.add('hidden')}$('#waitingCard').classList.add('hidden');$('#playCard').classList.remove('hidden');$('#studentProgressText').textContent=`第 ${s.questionIndex+1}/${s.totalQuestions} 題`;$('#studentScore').textContent=`${s.me?.score||0} 分`;$('#studentQuestion').textContent=s.currentQuestion.text;renderStudentAnswers(s.currentQuestion,s.me?.answeredCurrent)}
function renderStudentAnswers(q,answered){$('#studentAnswers').innerHTML=q.options.map((o,i)=>`<button class="answer-choice ${studentState.selected.includes(i)?'selected':''}" data-i="${i}" ${answered?'disabled':''}>${esc(o)}</button>`).join('');$$('.answer-choice').forEach(b=>b.onclick=()=>{if(answered)return;const i=+b.dataset.i;if(q.type==='multiple'){studentState.selected=studentState.selected.includes(i)?studentState.selected.filter(x=>x!==i):[...studentState.selected,i]}else studentState.selected=[i];renderStudentAnswers(q,false)});$('#submitAnswerBtn').disabled=!!answered;$('#submitAnswerBtn').textContent=answered?'本題已作答':'送出答案'}
$('#submitAnswerBtn').onclick=async()=>{try{if(!studentState.selected.length)throw new Error('請先選擇答案');const s=studentState.session,d=await api('submitAnswer',{pin:studentState.pin,participantId:studentState.participantId,questionIndex:s.questionIndex,selected:studentState.selected});$('#answerFeedback').classList.remove('hidden');$('#answerFeedback').textContent=d.correct?`答對了！＋${d.points} 分`:'再想一想，本題未得分。';await refreshStudent()}catch(e){toast(e.message)}};
prefillPin();
if(location.hash==='#join'||new URLSearchParams(location.search).has('pin'))showView('student');
